services:
  db:
    image: "postgres"
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - pgnetwork

  backend:
    image: "docker-spring-boot-postgres:latest"
    build:
      context: ./backend
    ports:
      - "8080:8080"
    container_name: backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - pgnetwork

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_BACKEND_URL: http://localhost:8080
      CHOKIDAR_USEPOLLING: true

networks:
  pgnetwork:
    driver: bridge

volumes:
  postgres_data:
