/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CakeRouteImport } from './routes/cake'
import { Route as IndexRouteImport } from './routes/index'

const CakeRoute = CakeRouteImport.update({
  id: '/cake',
  path: '/cake',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cake': typeof CakeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cake': typeof CakeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cake': typeof CakeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cake'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cake'
  id: '__root__' | '/' | '/cake'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CakeRoute: typeof CakeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cake': {
      id: '/cake'
      path: '/cake'
      fullPath: '/cake'
      preLoaderRoute: typeof CakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CakeRoute: CakeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
