/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVendasPorSessaoRouteImport } from './routes/app/vendas/por-sessao'
import { Route as AppVendasPorDiaRouteImport } from './routes/app/vendas/por-dia'
import { Route as AppSessoesPreEstreiasRouteImport } from './routes/app/sessoes/pre-estreias'
import { Route as AppSessoesOcupacaoRouteImport } from './routes/app/sessoes/ocupacao'
import { Route as AppEstatisticasSessoesRouteImport } from './routes/app/estatisticas/sessoes'
import { Route as AppEstatisticasBilheteriaRouteImport } from './routes/app/estatisticas/bilheteria'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVendasPorSessaoRoute = AppVendasPorSessaoRouteImport.update({
  id: '/vendas/por-sessao',
  path: '/vendas/por-sessao',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVendasPorDiaRoute = AppVendasPorDiaRouteImport.update({
  id: '/vendas/por-dia',
  path: '/vendas/por-dia',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSessoesPreEstreiasRoute = AppSessoesPreEstreiasRouteImport.update({
  id: '/sessoes/pre-estreias',
  path: '/sessoes/pre-estreias',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSessoesOcupacaoRoute = AppSessoesOcupacaoRouteImport.update({
  id: '/sessoes/ocupacao',
  path: '/sessoes/ocupacao',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEstatisticasSessoesRoute = AppEstatisticasSessoesRouteImport.update({
  id: '/estatisticas/sessoes',
  path: '/estatisticas/sessoes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEstatisticasBilheteriaRoute =
  AppEstatisticasBilheteriaRouteImport.update({
    id: '/estatisticas/bilheteria',
    path: '/estatisticas/bilheteria',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/estatisticas/bilheteria': typeof AppEstatisticasBilheteriaRoute
  '/app/estatisticas/sessoes': typeof AppEstatisticasSessoesRoute
  '/app/sessoes/ocupacao': typeof AppSessoesOcupacaoRoute
  '/app/sessoes/pre-estreias': typeof AppSessoesPreEstreiasRoute
  '/app/vendas/por-dia': typeof AppVendasPorDiaRoute
  '/app/vendas/por-sessao': typeof AppVendasPorSessaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/estatisticas/bilheteria': typeof AppEstatisticasBilheteriaRoute
  '/app/estatisticas/sessoes': typeof AppEstatisticasSessoesRoute
  '/app/sessoes/ocupacao': typeof AppSessoesOcupacaoRoute
  '/app/sessoes/pre-estreias': typeof AppSessoesPreEstreiasRoute
  '/app/vendas/por-dia': typeof AppVendasPorDiaRoute
  '/app/vendas/por-sessao': typeof AppVendasPorSessaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/estatisticas/bilheteria': typeof AppEstatisticasBilheteriaRoute
  '/app/estatisticas/sessoes': typeof AppEstatisticasSessoesRoute
  '/app/sessoes/ocupacao': typeof AppSessoesOcupacaoRoute
  '/app/sessoes/pre-estreias': typeof AppSessoesPreEstreiasRoute
  '/app/vendas/por-dia': typeof AppVendasPorDiaRoute
  '/app/vendas/por-sessao': typeof AppVendasPorSessaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/estatisticas/bilheteria'
    | '/app/estatisticas/sessoes'
    | '/app/sessoes/ocupacao'
    | '/app/sessoes/pre-estreias'
    | '/app/vendas/por-dia'
    | '/app/vendas/por-sessao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/estatisticas/bilheteria'
    | '/app/estatisticas/sessoes'
    | '/app/sessoes/ocupacao'
    | '/app/sessoes/pre-estreias'
    | '/app/vendas/por-dia'
    | '/app/vendas/por-sessao'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/estatisticas/bilheteria'
    | '/app/estatisticas/sessoes'
    | '/app/sessoes/ocupacao'
    | '/app/sessoes/pre-estreias'
    | '/app/vendas/por-dia'
    | '/app/vendas/por-sessao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/vendas/por-sessao': {
      id: '/app/vendas/por-sessao'
      path: '/vendas/por-sessao'
      fullPath: '/app/vendas/por-sessao'
      preLoaderRoute: typeof AppVendasPorSessaoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/vendas/por-dia': {
      id: '/app/vendas/por-dia'
      path: '/vendas/por-dia'
      fullPath: '/app/vendas/por-dia'
      preLoaderRoute: typeof AppVendasPorDiaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/sessoes/pre-estreias': {
      id: '/app/sessoes/pre-estreias'
      path: '/sessoes/pre-estreias'
      fullPath: '/app/sessoes/pre-estreias'
      preLoaderRoute: typeof AppSessoesPreEstreiasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/sessoes/ocupacao': {
      id: '/app/sessoes/ocupacao'
      path: '/sessoes/ocupacao'
      fullPath: '/app/sessoes/ocupacao'
      preLoaderRoute: typeof AppSessoesOcupacaoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/estatisticas/sessoes': {
      id: '/app/estatisticas/sessoes'
      path: '/estatisticas/sessoes'
      fullPath: '/app/estatisticas/sessoes'
      preLoaderRoute: typeof AppEstatisticasSessoesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/estatisticas/bilheteria': {
      id: '/app/estatisticas/bilheteria'
      path: '/estatisticas/bilheteria'
      fullPath: '/app/estatisticas/bilheteria'
      preLoaderRoute: typeof AppEstatisticasBilheteriaRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppEstatisticasBilheteriaRoute: typeof AppEstatisticasBilheteriaRoute
  AppEstatisticasSessoesRoute: typeof AppEstatisticasSessoesRoute
  AppSessoesOcupacaoRoute: typeof AppSessoesOcupacaoRoute
  AppSessoesPreEstreiasRoute: typeof AppSessoesPreEstreiasRoute
  AppVendasPorDiaRoute: typeof AppVendasPorDiaRoute
  AppVendasPorSessaoRoute: typeof AppVendasPorSessaoRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppEstatisticasBilheteriaRoute: AppEstatisticasBilheteriaRoute,
  AppEstatisticasSessoesRoute: AppEstatisticasSessoesRoute,
  AppSessoesOcupacaoRoute: AppSessoesOcupacaoRoute,
  AppSessoesPreEstreiasRoute: AppSessoesPreEstreiasRoute,
  AppVendasPorDiaRoute: AppVendasPorDiaRoute,
  AppVendasPorSessaoRoute: AppVendasPorSessaoRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
