/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVendasSnacksRouteImport } from './routes/app/vendas/snacks'
import { Route as AppVendasPorSessaoRouteImport } from './routes/app/vendas/por-sessao'
import { Route as AppVendasPorDiaRouteImport } from './routes/app/vendas/por-dia'
import { Route as AppVendasFormaPagamentoRouteImport } from './routes/app/vendas/forma-pagamento'
import { Route as AppVendasColecionaveisRouteImport } from './routes/app/vendas/colecionaveis'
import { Route as AppSessoesPreEstreiasRouteImport } from './routes/app/sessoes/pre-estreias'
import { Route as AppSessoesOcupacaoRouteImport } from './routes/app/sessoes/ocupacao'
import { Route as AppPontosProdutosResgatadosRouteImport } from './routes/app/pontos/produtos-resgatados'
import { Route as AppFilmesPorDiretorRouteImport } from './routes/app/filmes/por-diretor'
import { Route as AppFilmesGeneroPorDiretorRouteImport } from './routes/app/filmes/genero-por-diretor'
import { Route as AppFilmesEmCartazGeneroRouteImport } from './routes/app/filmes/em-cartaz-genero'
import { Route as AppFilmesAtoresPorFilmeRouteImport } from './routes/app/filmes/atores-por-filme'
import { Route as AppFilmesAtoresPopularesRouteImport } from './routes/app/filmes/atores-populares'
import { Route as AppEstatisticasSessoesRouteImport } from './routes/app/estatisticas/sessoes'
import { Route as AppEstatisticasDuracaoMediaGeneroRouteImport } from './routes/app/estatisticas/duracao-media-genero'
import { Route as AppEstatisticasBilheteriaPorGeneroRouteImport } from './routes/app/estatisticas/bilheteria-por-genero'
import { Route as AppEstatisticasBilheteriaPorDiretorRouteImport } from './routes/app/estatisticas/bilheteria-por-diretor'
import { Route as AppEstatisticasBilheteriaRouteImport } from './routes/app/estatisticas/bilheteria'
import { Route as AppClientesSemMeiaRouteImport } from './routes/app/clientes/sem-meia'
import { Route as AppClientesRankingRouteImport } from './routes/app/clientes/ranking'
import { Route as AppClientesPorFilmeRouteImport } from './routes/app/clientes/por-filme'
import { Route as AppClientesPontosRouteImport } from './routes/app/clientes/pontos'
import { Route as AppClientesEstudantilRouteImport } from './routes/app/clientes/estudantil'
import { Route as AppClientesIdadeGenerosRouteImport } from './routes/app/clientes/idade/generos'
import { Route as AppClientesIdadeFilmesRouteImport } from './routes/app/clientes/idade/filmes'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVendasSnacksRoute = AppVendasSnacksRouteImport.update({
  id: '/vendas/snacks',
  path: '/vendas/snacks',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVendasPorSessaoRoute = AppVendasPorSessaoRouteImport.update({
  id: '/vendas/por-sessao',
  path: '/vendas/por-sessao',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVendasPorDiaRoute = AppVendasPorDiaRouteImport.update({
  id: '/vendas/por-dia',
  path: '/vendas/por-dia',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVendasFormaPagamentoRoute = AppVendasFormaPagamentoRouteImport.update({
  id: '/vendas/forma-pagamento',
  path: '/vendas/forma-pagamento',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVendasColecionaveisRoute = AppVendasColecionaveisRouteImport.update({
  id: '/vendas/colecionaveis',
  path: '/vendas/colecionaveis',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSessoesPreEstreiasRoute = AppSessoesPreEstreiasRouteImport.update({
  id: '/sessoes/pre-estreias',
  path: '/sessoes/pre-estreias',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSessoesOcupacaoRoute = AppSessoesOcupacaoRouteImport.update({
  id: '/sessoes/ocupacao',
  path: '/sessoes/ocupacao',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPontosProdutosResgatadosRoute =
  AppPontosProdutosResgatadosRouteImport.update({
    id: '/pontos/produtos-resgatados',
    path: '/pontos/produtos-resgatados',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppFilmesPorDiretorRoute = AppFilmesPorDiretorRouteImport.update({
  id: '/filmes/por-diretor',
  path: '/filmes/por-diretor',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFilmesGeneroPorDiretorRoute =
  AppFilmesGeneroPorDiretorRouteImport.update({
    id: '/filmes/genero-por-diretor',
    path: '/filmes/genero-por-diretor',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppFilmesEmCartazGeneroRoute = AppFilmesEmCartazGeneroRouteImport.update({
  id: '/filmes/em-cartaz-genero',
  path: '/filmes/em-cartaz-genero',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFilmesAtoresPorFilmeRoute = AppFilmesAtoresPorFilmeRouteImport.update({
  id: '/filmes/atores-por-filme',
  path: '/filmes/atores-por-filme',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFilmesAtoresPopularesRoute =
  AppFilmesAtoresPopularesRouteImport.update({
    id: '/filmes/atores-populares',
    path: '/filmes/atores-populares',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppEstatisticasSessoesRoute = AppEstatisticasSessoesRouteImport.update({
  id: '/estatisticas/sessoes',
  path: '/estatisticas/sessoes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEstatisticasDuracaoMediaGeneroRoute =
  AppEstatisticasDuracaoMediaGeneroRouteImport.update({
    id: '/estatisticas/duracao-media-genero',
    path: '/estatisticas/duracao-media-genero',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppEstatisticasBilheteriaPorGeneroRoute =
  AppEstatisticasBilheteriaPorGeneroRouteImport.update({
    id: '/estatisticas/bilheteria-por-genero',
    path: '/estatisticas/bilheteria-por-genero',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppEstatisticasBilheteriaPorDiretorRoute =
  AppEstatisticasBilheteriaPorDiretorRouteImport.update({
    id: '/estatisticas/bilheteria-por-diretor',
    path: '/estatisticas/bilheteria-por-diretor',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppEstatisticasBilheteriaRoute =
  AppEstatisticasBilheteriaRouteImport.update({
    id: '/estatisticas/bilheteria',
    path: '/estatisticas/bilheteria',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppClientesSemMeiaRoute = AppClientesSemMeiaRouteImport.update({
  id: '/clientes/sem-meia',
  path: '/clientes/sem-meia',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientesRankingRoute = AppClientesRankingRouteImport.update({
  id: '/clientes/ranking',
  path: '/clientes/ranking',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientesPorFilmeRoute = AppClientesPorFilmeRouteImport.update({
  id: '/clientes/por-filme',
  path: '/clientes/por-filme',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientesPontosRoute = AppClientesPontosRouteImport.update({
  id: '/clientes/pontos',
  path: '/clientes/pontos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientesEstudantilRoute = AppClientesEstudantilRouteImport.update({
  id: '/clientes/estudantil',
  path: '/clientes/estudantil',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientesIdadeGenerosRoute = AppClientesIdadeGenerosRouteImport.update({
  id: '/clientes/idade/generos',
  path: '/clientes/idade/generos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientesIdadeFilmesRoute = AppClientesIdadeFilmesRouteImport.update({
  id: '/clientes/idade/filmes',
  path: '/clientes/idade/filmes',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/clientes/estudantil': typeof AppClientesEstudantilRoute
  '/app/clientes/pontos': typeof AppClientesPontosRoute
  '/app/clientes/por-filme': typeof AppClientesPorFilmeRoute
  '/app/clientes/ranking': typeof AppClientesRankingRoute
  '/app/clientes/sem-meia': typeof AppClientesSemMeiaRoute
  '/app/estatisticas/bilheteria': typeof AppEstatisticasBilheteriaRoute
  '/app/estatisticas/bilheteria-por-diretor': typeof AppEstatisticasBilheteriaPorDiretorRoute
  '/app/estatisticas/bilheteria-por-genero': typeof AppEstatisticasBilheteriaPorGeneroRoute
  '/app/estatisticas/duracao-media-genero': typeof AppEstatisticasDuracaoMediaGeneroRoute
  '/app/estatisticas/sessoes': typeof AppEstatisticasSessoesRoute
  '/app/filmes/atores-populares': typeof AppFilmesAtoresPopularesRoute
  '/app/filmes/atores-por-filme': typeof AppFilmesAtoresPorFilmeRoute
  '/app/filmes/em-cartaz-genero': typeof AppFilmesEmCartazGeneroRoute
  '/app/filmes/genero-por-diretor': typeof AppFilmesGeneroPorDiretorRoute
  '/app/filmes/por-diretor': typeof AppFilmesPorDiretorRoute
  '/app/pontos/produtos-resgatados': typeof AppPontosProdutosResgatadosRoute
  '/app/sessoes/ocupacao': typeof AppSessoesOcupacaoRoute
  '/app/sessoes/pre-estreias': typeof AppSessoesPreEstreiasRoute
  '/app/vendas/colecionaveis': typeof AppVendasColecionaveisRoute
  '/app/vendas/forma-pagamento': typeof AppVendasFormaPagamentoRoute
  '/app/vendas/por-dia': typeof AppVendasPorDiaRoute
  '/app/vendas/por-sessao': typeof AppVendasPorSessaoRoute
  '/app/vendas/snacks': typeof AppVendasSnacksRoute
  '/app/clientes/idade/filmes': typeof AppClientesIdadeFilmesRoute
  '/app/clientes/idade/generos': typeof AppClientesIdadeGenerosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/clientes/estudantil': typeof AppClientesEstudantilRoute
  '/app/clientes/pontos': typeof AppClientesPontosRoute
  '/app/clientes/por-filme': typeof AppClientesPorFilmeRoute
  '/app/clientes/ranking': typeof AppClientesRankingRoute
  '/app/clientes/sem-meia': typeof AppClientesSemMeiaRoute
  '/app/estatisticas/bilheteria': typeof AppEstatisticasBilheteriaRoute
  '/app/estatisticas/bilheteria-por-diretor': typeof AppEstatisticasBilheteriaPorDiretorRoute
  '/app/estatisticas/bilheteria-por-genero': typeof AppEstatisticasBilheteriaPorGeneroRoute
  '/app/estatisticas/duracao-media-genero': typeof AppEstatisticasDuracaoMediaGeneroRoute
  '/app/estatisticas/sessoes': typeof AppEstatisticasSessoesRoute
  '/app/filmes/atores-populares': typeof AppFilmesAtoresPopularesRoute
  '/app/filmes/atores-por-filme': typeof AppFilmesAtoresPorFilmeRoute
  '/app/filmes/em-cartaz-genero': typeof AppFilmesEmCartazGeneroRoute
  '/app/filmes/genero-por-diretor': typeof AppFilmesGeneroPorDiretorRoute
  '/app/filmes/por-diretor': typeof AppFilmesPorDiretorRoute
  '/app/pontos/produtos-resgatados': typeof AppPontosProdutosResgatadosRoute
  '/app/sessoes/ocupacao': typeof AppSessoesOcupacaoRoute
  '/app/sessoes/pre-estreias': typeof AppSessoesPreEstreiasRoute
  '/app/vendas/colecionaveis': typeof AppVendasColecionaveisRoute
  '/app/vendas/forma-pagamento': typeof AppVendasFormaPagamentoRoute
  '/app/vendas/por-dia': typeof AppVendasPorDiaRoute
  '/app/vendas/por-sessao': typeof AppVendasPorSessaoRoute
  '/app/vendas/snacks': typeof AppVendasSnacksRoute
  '/app/clientes/idade/filmes': typeof AppClientesIdadeFilmesRoute
  '/app/clientes/idade/generos': typeof AppClientesIdadeGenerosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/clientes/estudantil': typeof AppClientesEstudantilRoute
  '/app/clientes/pontos': typeof AppClientesPontosRoute
  '/app/clientes/por-filme': typeof AppClientesPorFilmeRoute
  '/app/clientes/ranking': typeof AppClientesRankingRoute
  '/app/clientes/sem-meia': typeof AppClientesSemMeiaRoute
  '/app/estatisticas/bilheteria': typeof AppEstatisticasBilheteriaRoute
  '/app/estatisticas/bilheteria-por-diretor': typeof AppEstatisticasBilheteriaPorDiretorRoute
  '/app/estatisticas/bilheteria-por-genero': typeof AppEstatisticasBilheteriaPorGeneroRoute
  '/app/estatisticas/duracao-media-genero': typeof AppEstatisticasDuracaoMediaGeneroRoute
  '/app/estatisticas/sessoes': typeof AppEstatisticasSessoesRoute
  '/app/filmes/atores-populares': typeof AppFilmesAtoresPopularesRoute
  '/app/filmes/atores-por-filme': typeof AppFilmesAtoresPorFilmeRoute
  '/app/filmes/em-cartaz-genero': typeof AppFilmesEmCartazGeneroRoute
  '/app/filmes/genero-por-diretor': typeof AppFilmesGeneroPorDiretorRoute
  '/app/filmes/por-diretor': typeof AppFilmesPorDiretorRoute
  '/app/pontos/produtos-resgatados': typeof AppPontosProdutosResgatadosRoute
  '/app/sessoes/ocupacao': typeof AppSessoesOcupacaoRoute
  '/app/sessoes/pre-estreias': typeof AppSessoesPreEstreiasRoute
  '/app/vendas/colecionaveis': typeof AppVendasColecionaveisRoute
  '/app/vendas/forma-pagamento': typeof AppVendasFormaPagamentoRoute
  '/app/vendas/por-dia': typeof AppVendasPorDiaRoute
  '/app/vendas/por-sessao': typeof AppVendasPorSessaoRoute
  '/app/vendas/snacks': typeof AppVendasSnacksRoute
  '/app/clientes/idade/filmes': typeof AppClientesIdadeFilmesRoute
  '/app/clientes/idade/generos': typeof AppClientesIdadeGenerosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/clientes/estudantil'
    | '/app/clientes/pontos'
    | '/app/clientes/por-filme'
    | '/app/clientes/ranking'
    | '/app/clientes/sem-meia'
    | '/app/estatisticas/bilheteria'
    | '/app/estatisticas/bilheteria-por-diretor'
    | '/app/estatisticas/bilheteria-por-genero'
    | '/app/estatisticas/duracao-media-genero'
    | '/app/estatisticas/sessoes'
    | '/app/filmes/atores-populares'
    | '/app/filmes/atores-por-filme'
    | '/app/filmes/em-cartaz-genero'
    | '/app/filmes/genero-por-diretor'
    | '/app/filmes/por-diretor'
    | '/app/pontos/produtos-resgatados'
    | '/app/sessoes/ocupacao'
    | '/app/sessoes/pre-estreias'
    | '/app/vendas/colecionaveis'
    | '/app/vendas/forma-pagamento'
    | '/app/vendas/por-dia'
    | '/app/vendas/por-sessao'
    | '/app/vendas/snacks'
    | '/app/clientes/idade/filmes'
    | '/app/clientes/idade/generos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/clientes/estudantil'
    | '/app/clientes/pontos'
    | '/app/clientes/por-filme'
    | '/app/clientes/ranking'
    | '/app/clientes/sem-meia'
    | '/app/estatisticas/bilheteria'
    | '/app/estatisticas/bilheteria-por-diretor'
    | '/app/estatisticas/bilheteria-por-genero'
    | '/app/estatisticas/duracao-media-genero'
    | '/app/estatisticas/sessoes'
    | '/app/filmes/atores-populares'
    | '/app/filmes/atores-por-filme'
    | '/app/filmes/em-cartaz-genero'
    | '/app/filmes/genero-por-diretor'
    | '/app/filmes/por-diretor'
    | '/app/pontos/produtos-resgatados'
    | '/app/sessoes/ocupacao'
    | '/app/sessoes/pre-estreias'
    | '/app/vendas/colecionaveis'
    | '/app/vendas/forma-pagamento'
    | '/app/vendas/por-dia'
    | '/app/vendas/por-sessao'
    | '/app/vendas/snacks'
    | '/app/clientes/idade/filmes'
    | '/app/clientes/idade/generos'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/clientes/estudantil'
    | '/app/clientes/pontos'
    | '/app/clientes/por-filme'
    | '/app/clientes/ranking'
    | '/app/clientes/sem-meia'
    | '/app/estatisticas/bilheteria'
    | '/app/estatisticas/bilheteria-por-diretor'
    | '/app/estatisticas/bilheteria-por-genero'
    | '/app/estatisticas/duracao-media-genero'
    | '/app/estatisticas/sessoes'
    | '/app/filmes/atores-populares'
    | '/app/filmes/atores-por-filme'
    | '/app/filmes/em-cartaz-genero'
    | '/app/filmes/genero-por-diretor'
    | '/app/filmes/por-diretor'
    | '/app/pontos/produtos-resgatados'
    | '/app/sessoes/ocupacao'
    | '/app/sessoes/pre-estreias'
    | '/app/vendas/colecionaveis'
    | '/app/vendas/forma-pagamento'
    | '/app/vendas/por-dia'
    | '/app/vendas/por-sessao'
    | '/app/vendas/snacks'
    | '/app/clientes/idade/filmes'
    | '/app/clientes/idade/generos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/vendas/snacks': {
      id: '/app/vendas/snacks'
      path: '/vendas/snacks'
      fullPath: '/app/vendas/snacks'
      preLoaderRoute: typeof AppVendasSnacksRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/vendas/por-sessao': {
      id: '/app/vendas/por-sessao'
      path: '/vendas/por-sessao'
      fullPath: '/app/vendas/por-sessao'
      preLoaderRoute: typeof AppVendasPorSessaoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/vendas/por-dia': {
      id: '/app/vendas/por-dia'
      path: '/vendas/por-dia'
      fullPath: '/app/vendas/por-dia'
      preLoaderRoute: typeof AppVendasPorDiaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/vendas/forma-pagamento': {
      id: '/app/vendas/forma-pagamento'
      path: '/vendas/forma-pagamento'
      fullPath: '/app/vendas/forma-pagamento'
      preLoaderRoute: typeof AppVendasFormaPagamentoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/vendas/colecionaveis': {
      id: '/app/vendas/colecionaveis'
      path: '/vendas/colecionaveis'
      fullPath: '/app/vendas/colecionaveis'
      preLoaderRoute: typeof AppVendasColecionaveisRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/sessoes/pre-estreias': {
      id: '/app/sessoes/pre-estreias'
      path: '/sessoes/pre-estreias'
      fullPath: '/app/sessoes/pre-estreias'
      preLoaderRoute: typeof AppSessoesPreEstreiasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/sessoes/ocupacao': {
      id: '/app/sessoes/ocupacao'
      path: '/sessoes/ocupacao'
      fullPath: '/app/sessoes/ocupacao'
      preLoaderRoute: typeof AppSessoesOcupacaoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/pontos/produtos-resgatados': {
      id: '/app/pontos/produtos-resgatados'
      path: '/pontos/produtos-resgatados'
      fullPath: '/app/pontos/produtos-resgatados'
      preLoaderRoute: typeof AppPontosProdutosResgatadosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/filmes/por-diretor': {
      id: '/app/filmes/por-diretor'
      path: '/filmes/por-diretor'
      fullPath: '/app/filmes/por-diretor'
      preLoaderRoute: typeof AppFilmesPorDiretorRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/filmes/genero-por-diretor': {
      id: '/app/filmes/genero-por-diretor'
      path: '/filmes/genero-por-diretor'
      fullPath: '/app/filmes/genero-por-diretor'
      preLoaderRoute: typeof AppFilmesGeneroPorDiretorRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/filmes/em-cartaz-genero': {
      id: '/app/filmes/em-cartaz-genero'
      path: '/filmes/em-cartaz-genero'
      fullPath: '/app/filmes/em-cartaz-genero'
      preLoaderRoute: typeof AppFilmesEmCartazGeneroRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/filmes/atores-por-filme': {
      id: '/app/filmes/atores-por-filme'
      path: '/filmes/atores-por-filme'
      fullPath: '/app/filmes/atores-por-filme'
      preLoaderRoute: typeof AppFilmesAtoresPorFilmeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/filmes/atores-populares': {
      id: '/app/filmes/atores-populares'
      path: '/filmes/atores-populares'
      fullPath: '/app/filmes/atores-populares'
      preLoaderRoute: typeof AppFilmesAtoresPopularesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/estatisticas/sessoes': {
      id: '/app/estatisticas/sessoes'
      path: '/estatisticas/sessoes'
      fullPath: '/app/estatisticas/sessoes'
      preLoaderRoute: typeof AppEstatisticasSessoesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/estatisticas/duracao-media-genero': {
      id: '/app/estatisticas/duracao-media-genero'
      path: '/estatisticas/duracao-media-genero'
      fullPath: '/app/estatisticas/duracao-media-genero'
      preLoaderRoute: typeof AppEstatisticasDuracaoMediaGeneroRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/estatisticas/bilheteria-por-genero': {
      id: '/app/estatisticas/bilheteria-por-genero'
      path: '/estatisticas/bilheteria-por-genero'
      fullPath: '/app/estatisticas/bilheteria-por-genero'
      preLoaderRoute: typeof AppEstatisticasBilheteriaPorGeneroRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/estatisticas/bilheteria-por-diretor': {
      id: '/app/estatisticas/bilheteria-por-diretor'
      path: '/estatisticas/bilheteria-por-diretor'
      fullPath: '/app/estatisticas/bilheteria-por-diretor'
      preLoaderRoute: typeof AppEstatisticasBilheteriaPorDiretorRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/estatisticas/bilheteria': {
      id: '/app/estatisticas/bilheteria'
      path: '/estatisticas/bilheteria'
      fullPath: '/app/estatisticas/bilheteria'
      preLoaderRoute: typeof AppEstatisticasBilheteriaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/clientes/sem-meia': {
      id: '/app/clientes/sem-meia'
      path: '/clientes/sem-meia'
      fullPath: '/app/clientes/sem-meia'
      preLoaderRoute: typeof AppClientesSemMeiaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/clientes/ranking': {
      id: '/app/clientes/ranking'
      path: '/clientes/ranking'
      fullPath: '/app/clientes/ranking'
      preLoaderRoute: typeof AppClientesRankingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/clientes/por-filme': {
      id: '/app/clientes/por-filme'
      path: '/clientes/por-filme'
      fullPath: '/app/clientes/por-filme'
      preLoaderRoute: typeof AppClientesPorFilmeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/clientes/pontos': {
      id: '/app/clientes/pontos'
      path: '/clientes/pontos'
      fullPath: '/app/clientes/pontos'
      preLoaderRoute: typeof AppClientesPontosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/clientes/estudantil': {
      id: '/app/clientes/estudantil'
      path: '/clientes/estudantil'
      fullPath: '/app/clientes/estudantil'
      preLoaderRoute: typeof AppClientesEstudantilRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/clientes/idade/generos': {
      id: '/app/clientes/idade/generos'
      path: '/clientes/idade/generos'
      fullPath: '/app/clientes/idade/generos'
      preLoaderRoute: typeof AppClientesIdadeGenerosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/clientes/idade/filmes': {
      id: '/app/clientes/idade/filmes'
      path: '/clientes/idade/filmes'
      fullPath: '/app/clientes/idade/filmes'
      preLoaderRoute: typeof AppClientesIdadeFilmesRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppClientesEstudantilRoute: typeof AppClientesEstudantilRoute
  AppClientesPontosRoute: typeof AppClientesPontosRoute
  AppClientesPorFilmeRoute: typeof AppClientesPorFilmeRoute
  AppClientesRankingRoute: typeof AppClientesRankingRoute
  AppClientesSemMeiaRoute: typeof AppClientesSemMeiaRoute
  AppEstatisticasBilheteriaRoute: typeof AppEstatisticasBilheteriaRoute
  AppEstatisticasBilheteriaPorDiretorRoute: typeof AppEstatisticasBilheteriaPorDiretorRoute
  AppEstatisticasBilheteriaPorGeneroRoute: typeof AppEstatisticasBilheteriaPorGeneroRoute
  AppEstatisticasDuracaoMediaGeneroRoute: typeof AppEstatisticasDuracaoMediaGeneroRoute
  AppEstatisticasSessoesRoute: typeof AppEstatisticasSessoesRoute
  AppFilmesAtoresPopularesRoute: typeof AppFilmesAtoresPopularesRoute
  AppFilmesAtoresPorFilmeRoute: typeof AppFilmesAtoresPorFilmeRoute
  AppFilmesEmCartazGeneroRoute: typeof AppFilmesEmCartazGeneroRoute
  AppFilmesGeneroPorDiretorRoute: typeof AppFilmesGeneroPorDiretorRoute
  AppFilmesPorDiretorRoute: typeof AppFilmesPorDiretorRoute
  AppPontosProdutosResgatadosRoute: typeof AppPontosProdutosResgatadosRoute
  AppSessoesOcupacaoRoute: typeof AppSessoesOcupacaoRoute
  AppSessoesPreEstreiasRoute: typeof AppSessoesPreEstreiasRoute
  AppVendasColecionaveisRoute: typeof AppVendasColecionaveisRoute
  AppVendasFormaPagamentoRoute: typeof AppVendasFormaPagamentoRoute
  AppVendasPorDiaRoute: typeof AppVendasPorDiaRoute
  AppVendasPorSessaoRoute: typeof AppVendasPorSessaoRoute
  AppVendasSnacksRoute: typeof AppVendasSnacksRoute
  AppClientesIdadeFilmesRoute: typeof AppClientesIdadeFilmesRoute
  AppClientesIdadeGenerosRoute: typeof AppClientesIdadeGenerosRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppClientesEstudantilRoute: AppClientesEstudantilRoute,
  AppClientesPontosRoute: AppClientesPontosRoute,
  AppClientesPorFilmeRoute: AppClientesPorFilmeRoute,
  AppClientesRankingRoute: AppClientesRankingRoute,
  AppClientesSemMeiaRoute: AppClientesSemMeiaRoute,
  AppEstatisticasBilheteriaRoute: AppEstatisticasBilheteriaRoute,
  AppEstatisticasBilheteriaPorDiretorRoute:
    AppEstatisticasBilheteriaPorDiretorRoute,
  AppEstatisticasBilheteriaPorGeneroRoute:
    AppEstatisticasBilheteriaPorGeneroRoute,
  AppEstatisticasDuracaoMediaGeneroRoute:
    AppEstatisticasDuracaoMediaGeneroRoute,
  AppEstatisticasSessoesRoute: AppEstatisticasSessoesRoute,
  AppFilmesAtoresPopularesRoute: AppFilmesAtoresPopularesRoute,
  AppFilmesAtoresPorFilmeRoute: AppFilmesAtoresPorFilmeRoute,
  AppFilmesEmCartazGeneroRoute: AppFilmesEmCartazGeneroRoute,
  AppFilmesGeneroPorDiretorRoute: AppFilmesGeneroPorDiretorRoute,
  AppFilmesPorDiretorRoute: AppFilmesPorDiretorRoute,
  AppPontosProdutosResgatadosRoute: AppPontosProdutosResgatadosRoute,
  AppSessoesOcupacaoRoute: AppSessoesOcupacaoRoute,
  AppSessoesPreEstreiasRoute: AppSessoesPreEstreiasRoute,
  AppVendasColecionaveisRoute: AppVendasColecionaveisRoute,
  AppVendasFormaPagamentoRoute: AppVendasFormaPagamentoRoute,
  AppVendasPorDiaRoute: AppVendasPorDiaRoute,
  AppVendasPorSessaoRoute: AppVendasPorSessaoRoute,
  AppVendasSnacksRoute: AppVendasSnacksRoute,
  AppClientesIdadeFilmesRoute: AppClientesIdadeFilmesRoute,
  AppClientesIdadeGenerosRoute: AppClientesIdadeGenerosRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
